// Mock data for when database is not connected
export const MOCK_VEHICLES = [
  {
    id: '1',
    slug: 'ferrari-488-gtb-black',
    displayName: '2024 Ferrari 488 GTB',
    make: 'Ferrari',
    model: '488 GTB',
    year: 2024,
    category: 'SUPERCAR',
    bodyType: 'COUPE',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'RWD',
    seats: 2,
    doors: 2,
    engineSize: 3.9,
    engineType: 'V8 Twin-Turbo',
    horsePower: 670,
    torque: 760,
    topSpeed: 330,
    acceleration: 3.0,
    fuelConsumption: 11.4,
    features: ['F1-Trac Traction Control', 'E-Diff3 Electronic Differential', 'Ferrari Dynamic Enhancer', 'LED Headlights', 'Premium Leather Interior'],
    primaryImageUrl: '/Ferrari 488 - black.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 2999,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 1,
    licensePlate: 'DXB-F488',
    vin: 'ZFF68AFA0E0123456',
    trim: 'GTB',
    description: 'Experience the pinnacle of Italian automotive excellence with the Ferrari 488 GTB. This mid-engine supercar features a 3.9-liter V8 twin-turbo engine producing 670 horsepower, accelerating from 0-100 km/h in just 3.0 seconds. With its F1-derived aerodynamics, advanced traction control systems, and iconic Ferrari styling, the 488 GTB represents the perfect fusion of performance and artistry. Available at 2,999 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '2',
    slug: 'ferrari-488-gtb-red',
    displayName: '2024 Ferrari 488 GTB Red',
    make: 'Ferrari',
    model: '488 GTB',
    year: 2024,
    category: 'SUPERCAR',
    bodyType: 'COUPE',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'RWD',
    seats: 2,
    doors: 2,
    engineSize: 3.9,
    engineType: 'V8 Twin-Turbo',
    horsePower: 670,
    torque: 760,
    topSpeed: 330,
    acceleration: 3.0,
    fuelConsumption: 11.4,
    features: ['F1-Trac Traction Control', 'E-Diff3 Electronic Differential', 'Ferrari Dynamic Enhancer', 'LED Headlights', 'Premium Leather Interior'],
    primaryImageUrl: '/Ferrari 488 - red.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 2999,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 2,
    licensePlate: 'DXB-F488R',
    vin: 'ZFF68AFA0E0123457',
    trim: 'GTB',
    description: 'Experience the pinnacle of Italian automotive excellence with the Ferrari 488 GTB in iconic Rosso Corsa. This mid-engine supercar features a 3.9-liter V8 twin-turbo engine producing 670 horsepower, accelerating from 0-100 km/h in just 3.0 seconds. With its F1-derived aerodynamics, advanced traction control systems, and iconic Ferrari styling in the classic red finish, the 488 GTB represents the perfect fusion of performance and artistry. Available at 2,999 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '3',
    slug: 'mercedes-g63-amg',
    displayName: '2024 Mercedes-Benz G63 AMG',
    make: 'Mercedes-Benz',
    model: 'G63 AMG',
    year: 2024,
    category: 'SUV',
    bodyType: 'SUV',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 4.0,
    engineType: 'V8 Twin-Turbo',
    horsePower: 577,
    torque: 627,
    topSpeed: 220,
    acceleration: 4.5,
    fuelConsumption: 13.1,
    features: ['AMG Performance Exhaust', 'AMG Ride Control Suspension', 'Burmester Premium Sound', 'AMG Night Package', 'Panoramic Sunroof'],
    primaryImageUrl: '/G63-white.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 1999,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 3,
    licensePlate: 'DXB-G63',
    vin: 'WDC4632121F123456',
    trim: 'AMG G63',
    description: 'Experience the ultimate luxury SUV with the Mercedes-Benz G63 AMG. This iconic off-road legend features a 4.0-liter V8 twin-turbo engine producing 577 horsepower, accelerating from 0-100 km/h in just 4.5 seconds. With its legendary three-locking differentials, adaptive air suspension, and opulent interior featuring Burmester premium sound, the G63 AMG combines uncompromising off-road capability with supreme luxury. Available at 1,999 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '4',
    slug: 'lamborghini-urus-performante',
    displayName: '2024 Lamborghini Urus Performante',
    make: 'Lamborghini',
    model: 'Urus Performante',
    year: 2024,
    category: 'SUV',
    bodyType: 'SUV',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 4.0,
    engineType: 'V8 Twin-Turbo',
    horsePower: 666,
    torque: 627,
    topSpeed: 306,
    acceleration: 3.3,
    fuelConsumption: 12.7,
    features: ['Performante Aerodynamics', 'Adaptive Air Suspension', 'Carbon Ceramic Brakes', 'Lamborghini Infotainment', 'Premium Leather Interior'],
    primaryImageUrl: '/Lamborghini Urus Performante Blue.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 2499,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 4,
    licensePlate: 'DXB-URUS',
    vin: 'ZLA9UAA05L1234567',
    trim: 'Performante',
    description: 'Experience the ultimate super SUV with the Lamborghini Urus Performante. This high-performance SUV features a 4.0-liter V8 twin-turbo engine producing 666 horsepower, accelerating from 0-100 km/h in just 3.3 seconds. With its Performante aerodynamics, adaptive air suspension, and carbon ceramic brakes, the Urus Performante delivers supercar performance in an SUV package. Available at 2,499 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '5',
    slug: 'mclaren-720s',
    displayName: '2024 McLaren 720S',
    make: 'McLaren',
    model: '720S',
    year: 2024,
    category: 'SUPERCAR',
    bodyType: 'COUPE',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'RWD',
    seats: 2,
    doors: 2,
    engineSize: 4.0,
    engineType: 'V8 Twin-Turbo',
    horsePower: 710,
    torque: 568,
    topSpeed: 341,
    acceleration: 2.9,
    fuelConsumption: 10.7,
    features: ['Active Aerodynamics', 'ProActive Chassis Control', 'McLaren Track Telemetry', 'Bowers & Wilkins Audio', 'Carbon Fiber Monocage'],
    primaryImageUrl: '/McLaren Blue.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 3499,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 5,
    licensePlate: 'DXB-M720',
    vin: 'SBM12AA05LC123456',
    trim: '720S',
    description: 'Experience the pinnacle of British supercar engineering with the McLaren 720S. This mid-engine masterpiece features a 4.0-liter V8 twin-turbo engine producing 710 horsepower, accelerating from 0-100 km/h in just 2.9 seconds. With its active aerodynamics, ProActive chassis control, and carbon fiber monocage, the 720S delivers Formula 1-inspired performance on the road. Available at 3,499 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '6',
    slug: 'lamborghini-urus-hulk',
    displayName: '2024 Lamborghini Urus Hulk Green',
    make: 'Lamborghini',
    model: 'Urus',
    year: 2024,
    category: 'SUV',
    bodyType: 'SUV',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 4.0,
    engineType: 'V8 Twin-Turbo',
    horsePower: 641,
    torque: 627,
    topSpeed: 305,
    acceleration: 3.6,
    fuelConsumption: 12.7,
    features: ['Adaptive Air Suspension', 'Carbon Ceramic Brakes', 'Lamborghini Infotainment', 'Premium Leather Interior', 'Sport Exhaust System'],
    primaryImageUrl: '/Urus Hulk Green.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 2299,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 6,
    licensePlate: 'DXB-URUSH',
    vin: 'ZLA9UAA05L1234568',
    trim: 'Urus',
    description: 'Experience the ultimate super SUV with the Lamborghini Urus in striking Hulk Green. This high-performance SUV features a 4.0-liter V8 twin-turbo engine producing 641 horsepower, accelerating from 0-100 km/h in just 3.6 seconds. With its adaptive air suspension, carbon ceramic brakes, and distinctive green finish, the Urus delivers supercar performance in an SUV package. Available at 2,299 AED per day.',
    _count: { bookings: 0 }
  }
]

export const MOCK_BOOKINGS = []
export const MOCK_USERS = []
export const MOCK_ADDONS = []
