// Mock data for when database is not connected
export const MOCK_VEHICLES = [
  {
    id: '1',
    slug: 'bmw-m440-coupe',
    displayName: '2025 BMW M440 Coupé',
    make: 'BMW',
    model: 'M440',
    year: 2025,
    category: 'SPORTS',
    bodyType: 'COUPE',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 4,
    doors: 2,
    engineSize: 3.0,
    engineType: 'Inline-6 Turbo',
    horsePower: 374,
    torque: 500,
    topSpeed: 250,
    acceleration: 4.5,
    fuelConsumption: 8.5,
    features: ['M Sport Suspension', 'Adaptive LED Headlights', 'Harman Kardon Audio', 'M Sport Differential', 'Driving Assistant Professional'],
    primaryImageUrl: '/BMWM440_coupe.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 699,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 1,
    licensePlate: 'DXB-M440',
    vin: 'WBA53BK01NCG12345',
    trim: 'M440i xDrive',
    description: 'Experience the perfect blend of dynamic performance and everyday luxury with the BMW M440 Coupé. This sophisticated sports coupe features a powerful inline-6 turbocharged engine delivering 374 horsepower, propelling you from 0-100 km/h in just 4.5 seconds. With its aggressive M Sport styling, premium interior craftsmanship, and cutting-edge technology, the M440 represents the pinnacle of modern BMW engineering. Available now at our exclusive summer rates of 699 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '2',
    slug: 'mercedes-cle-53-amg',
    displayName: 'Mercedes Benz CLE 53 AMG',
    make: 'Mercedes-Benz',
    model: 'CLE 53 AMG',
    year: 2024,
    category: 'LUXURY',
    bodyType: 'COUPE',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 4,
    doors: 2,
    engineSize: 3.0,
    engineType: 'Inline-6 Turbo + EQ Boost',
    horsePower: 443,
    torque: 560,
    topSpeed: 250,
    acceleration: 4.0,
    fuelConsumption: 9.0,
    features: ['AMG Performance Exhaust', 'AMG Ride Control Suspension', 'Burmester Surround Sound', 'AMG Track Pace', 'MBUX Augmented Reality'],
    primaryImageUrl: '/CLE53_1.jpeg',
    images: [],
    priceRules: [{
      basePricePerDay: 699,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 2,
    licensePlate: 'DXB-CLE53',
    vin: 'WDD2383421F123456',
    trim: 'AMG 53 4MATIC+',
    description: 'The Mercedes-Benz CLE 53 AMG redefines the grand tourer with its seamless fusion of luxury and performance. Powered by a 3.0-liter inline-six engine enhanced with EQ Boost technology, it delivers an exhilarating 443 horsepower and reaches 100 km/h in just 4.0 seconds. The CLE 53 AMG showcases Mercedes\' commitment to excellence with its refined AMG performance exhaust, adaptive suspension, and meticulously crafted interior featuring Burmester surround sound. Reserve this masterpiece today at 699 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '3',
    slug: 'mercedes-c43-amg',
    displayName: 'Mercedes Benz C43 AMG',
    make: 'Mercedes-Benz',
    model: 'C43 AMG',
    year: 2024,
    category: 'LUXURY',
    bodyType: 'SEDAN',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 2.0,
    engineType: 'Inline-4 Turbo',
    horsePower: 408,
    torque: 500,
    topSpeed: 250,
    acceleration: 4.6,
    fuelConsumption: 8.8,
    features: ['AMG Sport Suspension', 'AMG Performance Steering Wheel', 'Burmester Sound System', 'AMG Night Package', 'Panoramic Sunroof'],
    primaryImageUrl: '/C43AMG_1.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 499,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 3,
    licensePlate: 'DXB-C43',
    vin: 'WDD2050851F123456',
    trim: 'AMG C43 4MATIC',
    description: 'Discover the Mercedes-Benz C43 AMG, where sports sedan performance meets executive comfort. This refined performance machine features a turbocharged 2.0-liter engine producing 408 horsepower, achieving 0-100 km/h in an impressive 4.6 seconds. The C43 AMG embodies the perfect daily driver with its AMG sport suspension, premium Burmester sound system, and sophisticated digital cockpit. Experience German engineering excellence at its finest, available from 499 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '4',
    slug: 'rox-01-vip',
    displayName: '2025 Rox 01 VIP',
    make: 'Rox',
    model: '01',
    year: 2025,
    category: 'SUV',
    bodyType: 'SUV',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'HYBRID',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 2.0,
    engineType: 'Plug-in Hybrid',
    horsePower: 320,
    torque: 480,
    topSpeed: 200,
    acceleration: 6.5,
    fuelConsumption: 2.5,
    features: ['1300 km Range', 'Plug-in Hybrid System', 'Premium Interior', 'Advanced Driver Assistance', 'Panoramic Glass Roof'],
    primaryImageUrl: '/Rox 01.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 699,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 4,
    licensePlate: 'DXB-ROX01',
    vin: 'ROX0125NC0001',
    trim: 'VIP',
    description: 'Introducing the 2025 Rox 01 VIP, the future of sustainable luxury mobility. This groundbreaking plug-in hybrid SUV offers an unprecedented 1,300 km range, combining eco-conscious engineering with uncompromising premium comfort. The Rox 01 VIP features advanced driver assistance systems, a meticulously appointed interior with luxury seating, and a panoramic glass roof that transforms every journey. Perfect for the discerning driver who values both performance and environmental responsibility. Available at 699 AED per day with no deposit required.',
    _count: { bookings: 0 }
  },
  {
    id: '5',
    slug: 'audi-rs3-daytona-grey',
    displayName: 'Audi RS3 Hatchback Daytona Grey',
    make: 'Audi',
    model: 'RS3',
    year: 2024,
    category: 'SPORTS',
    bodyType: 'HATCHBACK',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 2.5,
    engineType: 'Inline-5 Turbo',
    horsePower: 400,
    torque: 500,
    topSpeed: 290,
    acceleration: 3.8,
    fuelConsumption: 9.8,
    features: ['Quattro AWD', 'RS Sport Suspension Plus', 'RS Sport Exhaust', 'Bang & Olufsen Premium Sound', 'Matrix LED Headlights'],
    primaryImageUrl: '/RS3-Hatchback-Daytona.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 699,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 5,
    licensePlate: 'DXB-RS3D',
    vin: 'WAUZZZ8V3LA123456',
    trim: 'RS3 Sportback',
    description: 'The Audi RS3 Sportback in exclusive Daytona Grey represents the ultimate hot hatchback experience. Powered by Audi\'s legendary 2.5-liter turbocharged five-cylinder engine producing 400 horsepower, it accelerates from 0-100 km/h in a breathtaking 3.8 seconds. The RS3 combines everyday practicality with supercar performance, featuring Quattro all-wheel drive, RS Sport Suspension Plus, and a distinctive five-cylinder soundtrack enhanced by the RS Sport Exhaust. Finished in the striking Daytona Grey, this compact powerhouse is available at 699 AED per day.',
    _count: { bookings: 0 }
  },
  {
    id: '6',
    slug: 'audi-rs3-black',
    displayName: 'Audi RS3 Hatchback Black',
    make: 'Audi',
    model: 'RS3',
    year: 2024,
    category: 'SPORTS',
    bodyType: 'HATCHBACK',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 2.5,
    engineType: 'Inline-5 Turbo',
    horsePower: 400,
    torque: 500,
    topSpeed: 290,
    acceleration: 3.8,
    fuelConsumption: 9.8,
    features: ['Quattro AWD', 'RS Sport Suspension Plus', 'RS Sport Exhaust', 'Bang & Olufsen Premium Sound', 'Matrix LED Headlights'],
    primaryImageUrl: '/RS3HatchbackBlack-NotDaytona.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 699,
      weekendMultiplier: 1.0,
      weeklyDiscount: 0,
      monthlyDiscount: 0,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 250,
      extraKmPrice: 3,
      depositAmount: 0,
      isActive: true
    }],
    featured: true,
    featuredOrder: 6,
    licensePlate: 'DXB-RS3B',
    vin: 'WAUZZZ8V4LA123457',
    trim: 'RS3 Sportback',
    description: 'Experience the sophisticated menace of the Audi RS3 Sportback in timeless Black. This performance hatchback masterpiece houses a turbocharged 2.5-liter five-cylinder engine delivering 400 horsepower and an iconic engine note. With a 0-100 km/h time of just 3.8 seconds and Quattro all-wheel drive, the RS3 offers uncompromising performance wrapped in an elegant black exterior. The interior features Bang & Olufsen premium sound, Matrix LED headlights, and RS-specific sport seats. Perfect for those who demand both practicality and pulse-racing performance at 699 AED per day.',
    _count: { bookings: 0 }
  }
]

export const MOCK_BOOKINGS = []
export const MOCK_USERS = []
export const MOCK_ADDONS = []
